export interface Product {
  id: string
  name: string
  category: string
  price: number
  originalPrice?: number
  image: string
  description: string
  rating: number
  reviews: number
  inStock: boolean
  dosage?: string
  quantity?: string
  sku?: string
  bulkDiscounts?: BulkDiscount[]
}

export interface BulkDiscount {
  minQuantity: number
  maxQuantity: number
  discount: number // percentage
  label: string
}

export const bulkDiscountTiers: BulkDiscount[] = [
  { minQuantity: 5, maxQuantity: 9, discount: 10, label: "5-9 units: Save 10%" },
  { minQuantity: 10, maxQuantity: 19, discount: 15, label: "10-19 units: Save 15%" },
  { minQuantity: 20, maxQuantity: 49, discount: 20, label: "20-49 units: Save 20%" },
  { minQuantity: 50, maxQuantity: Number.POSITIVE_INFINITY, discount: 25, label: "50+ units: Save 25%" },
]

export const products: Product[] = [
  // PEPTIDES
  {
    id: "1",
    name: "Melanotan 2 (MT-2) 10mg",
    category: "Peptides",
    price: 36.95,
    originalPrice: 47.99,
    image: "/pharmaceutical-peptide-vial-medical.jpg",
    description:
      "Research-grade Melanotan 2 peptide for laboratory use. High purity formulation sourced from certified suppliers.",
    rating: 4.8,
    reviews: 247,
    inStock: true,
    dosage: "10mg",
    sku: "SR-WHME-JEVC",
    bulkDiscounts: bulkDiscountTiers,
  },
  {
    id: "2",
    name: "PT-141 (Bremelanotide) 10mg",
    category: "Peptides",
    price: 37.5,
    originalPrice: 59.99,
    image: "/peptide-research-compound-vial.jpg",
    description:
      "Premium research peptide PT-141 for scientific studies. Laboratory certified with 98% purity minimum.",
    rating: 4.9,
    reviews: 189,
    inStock: true,
    dosage: "10mg",
    sku: "SR-WHPT-SEVC",
    bulkDiscounts: bulkDiscountTiers,
  },
  {
    id: "3",
    name: "BPC 157 5mg",
    category: "Peptides",
    price: 47.25,
    originalPrice: 56.0,
    image: "/bpc-peptide-medical-research-vial.jpg",
    description: "Body Protection Compound 157 - Research grade peptide for laboratory research and analysis.",
    rating: 4.7,
    reviews: 312,
    inStock: true,
    dosage: "5mg",
    sku: "SG-BPC1-1571",
    bulkDiscounts: bulkDiscountTiers,
  },
  {
    id: "4",
    name: "CJC-1295 NO DAC and IPAMORELIN BLEND (2mg each = 4mg total)",
    category: "Peptides",
    price: 43.25,
    originalPrice: 55.79,
    image: "/research-peptide-compound-laboratory-vial.jpg",
    description: "Dual peptide blend combining CJC-1295 NO DAC and IPAMORELIN for comprehensive research applications.",
    rating: 4.6,
    reviews: 156,
    inStock: true,
    dosage: "2mg each",
    sku: "BL-CJCN-IPAM",
    bulkDiscounts: bulkDiscountTiers,
  },
  {
    id: "5",
    name: "BPC 157 and TB-500 BLEND (2mg each = 4mg total)",
    category: "Peptides",
    price: 45.99,
    originalPrice: 59.99,
    image: "https://revolutionhealth.org/cdn/shop/articles/BPC-157_-_TB-500_combination_peptide_revolution_vial.png?v=1750699974",
    description:
      "Synergistic peptide blend combining BPC 157 and TB-500 (Thymosin B4) for enhanced research potential.",
    rating: 4.7,
    reviews: 203,
    inStock: true,
    dosage: "2mg each",
    sku: "BL-BPC-TB500",
    bulkDiscounts: bulkDiscountTiers,
  },
  {
    id: "6",
    name: "SERMORELIN 2mg",
    category: "Peptides",
    price: 23.99,
    originalPrice: 33.0,
    image: "https://regenmdwellness.com/cdn/shop/files/SermorelinBottle.png?v=1743793455&width=1946",
    description: "Growth hormone-releasing hormone (GHRH) analog for advanced research purposes. USA sourced.",
    rating: 4.8,
    reviews: 178,
    inStock: true,
    dosage: "2mg",
    sku: "SR-WHPT-SERM",
    bulkDiscounts: bulkDiscountTiers,
  },
  {
    id: "7",
    name: "CJC-1295 with DAC, IPAM, GHRP-2 BLEND (2mg each = 6mg)",
    category: "Peptides",
    price: 69.25,
    originalPrice: 90.0,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRUTj3UmUK9tIIhDNzZlWwz1Md_sBhFv8fx5g&s",
    description: "Triple peptide blend for comprehensive research applications. Maximum potency formulation.",
    rating: 4.9,
    reviews: 289,
    inStock: true,
    dosage: "2mg each",
    sku: "BL-CJCD-IPAM-GHRP2",
    bulkDiscounts: bulkDiscountTiers,
  },
  {
    id: "8",
    name: "IPAMORELIN 2mg",
    category: "Peptides",
    price: 23.99,
    originalPrice: 33.0,
    image: "https://xlpeptides.com/wp-content/uploads/2024/06/VIal_Editable_label_final_HR_3500x3500-copy-scaled.webp",
    description: "Selective growth hormone secretagogue for research applications. High stability formulation.",
    rating: 4.8,
    reviews: 234,
    inStock: true,
    dosage: "2mg",
    sku: "SR-IPAM-JEVC",
    bulkDiscounts: bulkDiscountTiers,
  },
  {
    id: "9",
    name: "TB-500 (Thymosin B4) 2mg",
    category: "Peptides",
    price: 37.25,
    originalPrice: 47.99,
    image: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTTTOf_ybHPg9oX91KV3J8B64R9FMrFd-luudbR6ykI1ulfRTdswt_kWcprmDX6tI54JaI62GVKFoyxkPsTq1Ssl8Dw-85T_qkqSWQPgdGxLdSlAUJ3mO3Kew",
    description: "Thymosin B4 analog for tissue regeneration and cellular support research.",
    rating: 4.7,
    reviews: 167,
    inStock: true,
    dosage: "2mg",
    sku: "SG-TMB4-0502",
    bulkDiscounts: bulkDiscountTiers,
  },

  // SARMS AND LIQUIDS
  {
    id: "10",
    name: "Tadalafil 30mg/ml @ 30ml",
    category: "SARMS and Liquids",
    price: 32.5,
    originalPrice: 47.99,
    image: "/pharmaceutical-compound-liquid-research.jpg",
    description: "Research-grade pharmaceutical compound for laboratory analysis. PDE5 inhibitor class.",
    rating: 4.7,
    reviews: 203,
    inStock: true,
    quantity: "30ml",
    sku: "SR-CHEM-TDFL",
    bulkDiscounts: bulkDiscountTiers,
  },
  {
    id: "11",
    name: "Sildenafil Citrate 25mg/ml @ 30ml",
    category: "SARMS and Liquids",
    price: 29.5,
    originalPrice: 44.99,
    image: "/research-pharmaceutical-liquid-vial.jpg",
    description: "High-purity research compound for scientific investigation. Laboratory certified.",
    rating: 4.8,
    reviews: 178,
    inStock: true,
    quantity: "30ml",
    sku: "SR-CHEM-SILD",
    bulkDiscounts: bulkDiscountTiers,
  },
  {
    id: "12",
    name: "Tamoxifen Citrate 20mg/ml @ 30ml",
    category: "SARMS and Liquids",
    price: 28.5,
    originalPrice: 45.99,
    image: "/pharmaceutical-research-compound-bottle.jpg",
    description: "SERM compound for research applications. Pharmaceutical grade quality.",
    rating: 4.6,
    reviews: 124,
    inStock: true,
    quantity: "30ml",
    sku: "SR-CHEM-TAMX",
    bulkDiscounts: bulkDiscountTiers,
  },
  {
    id: "13",
    name: "Clenbuterol HCL 200mcg/ml @ 30ml",
    category: "SARMS and Liquids",
    price: 37.25,
    originalPrice: 49.99,
    image: "/research-pharmaceutical-compound-laboratory.jpg",
    description: "Thermogenic research compound for laboratory analysis. High concentration formulation.",
    rating: 4.7,
    reviews: 289,
    inStock: true,
    quantity: "30ml",
    sku: "SR-CHEM-CLEN",
    bulkDiscounts: bulkDiscountTiers,
  },
  {
    id: "14",
    name: "Anastrozole 1.5mg/ml @ 30ml",
    category: "SARMS and Liquids",
    price: 37.25,
    originalPrice: 47.99,
    image: "/quality-assurance-lab-testing.jpg",
    description: "Aromatase inhibitor for research purposes. Laboratory verified formulation.",
    rating: 4.6,
    reviews: 145,
    inStock: true,
    quantity: "30ml",
    sku: "SR-CHEM-ANZL",
    bulkDiscounts: bulkDiscountTiers,
  },
  {
    id: "15",
    name: "MK-677 25mg/ml @ 30ml",
    category: "SARMS and Liquids",
    price: 79.0,
    originalPrice: 115.0,
    image: "/pharmaceutical-research-peptide-vial-laboratory.jpg",
    description: "Growth hormone secretagogue research compound. Premium quality formulation.",
    rating: 4.8,
    reviews: 267,
    inStock: true,
    quantity: "30ml",
    sku: "SR-CHEM-MK67",
    bulkDiscounts: bulkDiscountTiers,
  },
  {
    id: "16",
    name: "GW-501516 (Cardarine) 10mg/ml @ 30ml",
    category: "SARMS and Liquids",
    price: 47.25,
    originalPrice: 64.99,
    image: "/peptide-products-showcase.jpg",
    description: "PPAR delta agonist for research applications. USA availability only.",
    rating: 4.7,
    reviews: 198,
    inStock: true,
    quantity: "30ml",
    sku: "SR-CHEM-GW50",
    bulkDiscounts: bulkDiscountTiers,
  },
  {
    id: "17",
    name: "RAD-140 10mg/mL @ 30mL",
    category: "SARMS and Liquids",
    price: 62.25,
    originalPrice: 99.0,
    image: "/hero-pharmaceutical-lab-research.jpg",
    description: "SARM compound for muscle research. Selective androgen receptor modulator.",
    rating: 4.8,
    reviews: 223,
    inStock: true,
    quantity: "30ml",
    sku: "SR-CHEM-RAD1",
    bulkDiscounts: bulkDiscountTiers,
  },
  {
    id: "18",
    name: "LGD-4033 10mg/ml @ 30ml",
    category: "SARMS and Liquids",
    price: 54.5,
    originalPrice: 79.99,
    image: "/wholesale-bulk-pricing-showcase.jpg",
    description: "Ligandrol research compound for targeted research applications.",
    rating: 4.7,
    reviews: 201,
    inStock: true,
    quantity: "30ml",
    sku: "SR-CHEM-LGD4",
    bulkDiscounts: bulkDiscountTiers,
  },
  {
    id: "19",
    name: "Ostarine (MK-2866) 25mg/ml @ 30ml",
    category: "SARMS and Liquids",
    price: 44.75,
    originalPrice: 64.99,
    image: "/sarm-liquid-premium.png",
    description: "Selective androgen receptor modulator for research. Enhanced bioavailability.",
    rating: 4.6,
    reviews: 176,
    inStock: true,
    quantity: "30ml",
    sku: "SR-CHEM-OST1",
    bulkDiscounts: bulkDiscountTiers,
  },

  // HEALTH SUPPLEMENTS
  {
    id: "20",
    name: "Vitamin B12 1000mcg Supplement",
    category: "Health Supplements",
    price: 12.99,
    originalPrice: 16.99,
    image: "/vitamin-supplement-bottle-health.jpg",
    description: "Professional-grade B12 supplement for energy, cognitive support, and nervous system health.",
    rating: 4.9,
    reviews: 445,
    inStock: true,
    sku: "SUP-VIT-B12",
  },
  {
    id: "21",
    name: "NAD+ Booster 250mg",
    category: "Health Supplements",
    price: 39.99,
    originalPrice: 49.99,
    image: "/nad-supplement-capsules-wellness.jpg",
    description: "Premium NAD+ precursor for cellular energy, mitochondrial function, and longevity support.",
    rating: 4.8,
    reviews: 367,
    inStock: true,
    sku: "SUP-NAD-250",
  },
  {
    id: "22",
    name: "Omega-3 Pro 1000mg",
    category: "Health Supplements",
    price: 18.5,
    originalPrice: 24.99,
    image: "/omega-3-supplement-fish-oil-bottle.jpg",
    description: "Advanced omega-3 formulation with EPA and DHA for cardiovascular and cognitive health.",
    rating: 4.7,
    reviews: 512,
    inStock: true,
    sku: "SUP-OMG3-1KMG",
  },
  {
    id: "23",
    name: "Magnesium Glycinate 400mg",
    category: "Health Supplements",
    price: 14.99,
    originalPrice: 19.99,
    image: "/supplement-capsules-premium.png",
    description: "Highly absorbable magnesium for muscle recovery, sleep quality, and stress management.",
    rating: 4.8,
    reviews: 289,
    inStock: true,
    sku: "SUP-MAG-400",
  },
  {
    id: "24",
    name: "L-Arginine Plus 500mg",
    category: "Health Supplements",
    price: 16.49,
    originalPrice: 21.99,
    image: "https://m.media-amazon.com/images/I/71Yn1-e37yL._AC_SL1500_.jpg",
    description: "Premium amino acid supplement for cardiovascular health and athletic performance.",
    rating: 4.6,
    reviews: 198,
    inStock: true,
    sku: "SUP-ARG-500",
  },
  {
    id: "25",
    name: "CoQ10 300mg Ubiquinone",
    category: "Health Supplements",
    price: 22.99,
    originalPrice: 29.99,
    image: "https://m.media-amazon.com/images/I/71-uR10f2TL._AC_SL1500_.jpg",
    description: "Premium CoQ10 for heart health, cellular energy production, and antioxidant support.",
    rating: 4.9,
    reviews: 334,
    inStock: true,
    sku: "SUP-COQ10-300",
  },

  // MEDICAL ACCESSORIES
  {
    id: "26",
    name: "Sterile Syringes 3ml (Box of 100)",
    category: "Medical Accessories",
    price: 16.99,
    originalPrice: 21.99,
    image: "/medical-syringes-sterile-healthcare.jpg",
    description: "Sterile, medical-grade syringes for research and professional use. Ultra-sharp needles.",
    rating: 4.9,
    reviews: 278,
    inStock: true,
    sku: "ACC-SYR-3ML-100",
  },
  {
    id: "27",
    name: "Sterile Needles 25G (Box of 100)",
    category: "Medical Accessories",
    price: 12.49,
    originalPrice: 16.99,
    image: "/medical-accessories-premium.png",
    description: "Individually wrapped sterile needles for safe injection and research applications.",
    rating: 4.8,
    reviews: 145,
    inStock: true,
    sku: "ACC-NEE-25G-100",
  },
  {
    id: "28",
    name: "Sterile Water 10ml (Box of 50)",
    category: "Medical Accessories",
    price: 9.99,
    originalPrice: 14.99,
    image: "/fast-secure-shipping.jpg",
    description: "Pharmaceutical-grade sterile water for dilution and preparation of research compounds.",
    rating: 4.9,
    reviews: 423,
    inStock: true,
    sku: "ACC-WATER-10ML",
  },
  {
    id: "29",
    name: "Alcohol Prep Pads (Box of 100)",
    category: "Medical Accessories",
    price: 7.49,
    originalPrice: 9.99,
    image: "https://m.media-amazon.com/images/I/61-L7kkkuDL._SL1200_.jpg",
    description: "Sterile alcohol preparation pads for injection site cleaning and sanitization.",
    rating: 4.8,
    reviews: 267,
    inStock: true,
    sku: "ACC-ALC-PADS-100",
  },
  {
    id: "30",
    name: "Sharps Container 2 Liter",
    category: "Medical Accessories",
    price: 14.99,
    originalPrice: 19.99,
    image: "https://m.media-amazon.com/images/I/71Y8J1nK7cL._AC_SL1500_.jpg",
    description: "Safety sharps container for proper disposal of medical needles and syringes.",
    rating: 4.9,
    reviews: 156,
    inStock: true,
    sku: "ACC-SHARP-2L",
  },
]

export const categories = [
  { id: "all", name: "All Products" },
  { id: "peptides", name: "Peptides" },
  { id: "sarms-and-liquids", name: "SARMS and Liquids" },
  { id: "supplements", name: "Health Supplements" },
  { id: "accessories", name: "Medical Accessories" },
]

// Helper function to calculate bulk discount
export function getBulkDiscount(quantity: number, discounts: BulkDiscount[] = bulkDiscountTiers): number {
  for (const tier of discounts) {
    if (quantity >= tier.minQuantity && quantity <= tier.maxQuantity) {
      return tier.discount
    }
  }
  return 0
}

// Helper function to calculate discounted price
export function getDiscountedPrice(
  price: number,
  quantity: number,
  discounts: BulkDiscount[] = bulkDiscountTiers,
): number {
  const discountPercent = getBulkDiscount(quantity, discounts)
  return price * (1 - discountPercent / 100)
}
